name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    name: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        cache: "npm"
    - name: Install dependencies
      run: npm install
    - name: Lint project
      run: npm run lint
    - name: Compile webpack
      run: npm run build
